[versions]
java = "17"

androidGradle = "8.9.3" # https://developer.android.com/reference/tools/gradle-api
androidCompileSDK = "35"
androidMinimalSDK = "28"

skroll = "1.4.1"
kotlin = "2.1.21" # https://github.com/JetBrains/kotlin/releases
kotlinxIo = "0.7.0" # https://github.com/Kotlin/kotlinx-io/releases
kotlinxDateTime = "0.6.2" # https://github.com/Kotlin/kotlinx-datetime/releases
kotlinxCoroutines = "1.10.2" # https://github.com/Kotlin/kotlinx.coroutines/releases
ktor = "3.1.3" # https://github.com/ktorio/ktor/releases
filament = "1.4.2" # https://git.karmakrafts.dev/kk/filament/-/releases
stately = "2.1.0" # https://github.com/touchlab/Stately/releases
dokka = "2.0.0" # https://github.com/Kotlin/dokka/releases
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
karmaConventions = "1.5.5"

[libraries]
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
stately-common = { module = "co.touchlab:stately-common", version.ref = "stately" }
stately-collections = { module = "co.touchlab:stately-collections", version.ref = "stately" }
filament-core = { module = "dev.karmakrafts.filament:filament-core", version.ref = "filament" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }